name: liquip
main: com.github.sqyyy.liquip.Liquip
version: 0.0.1-SNAPSHOT
api-version: 1.19
authors:
  - sqyyy
  - Skienex
website: https://github.com/sqyyy-jar/liquip/
libraries:
  - com.typesafe:config:1.4.2