name: liquip-core
main: com.github.sqyyy.liquip.core.Liquip
version: 0.0.1-SNAPSHOT
api-version: 1.19
authors:
  - sqyyy
  - Skienex
website: https://github.com/sqyyy-jar/liquip/
libraries:
  - com.typesafe:config:1.4.2
commands:
  liquip:
    usage: /liquip give <item>