name: liquip-example
main: com.github.sqyyy.liquip.example.LiquipExample
version: 0.0.1-SNAPSHOT
api-version: 1.19
authors:
  - sqyyy
  - Skienex
website: https://github.com/sqyyy-jar/liquip/
depend:
  - liquip-core