name: Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Checkout the gh-pages branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages
          path: gh-pages
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate Javadoc
        run: ./gradlew javadoc
        env:
          GRADLE_GITHUB_USERNAME: ${{ github.actor }}
          GRADLE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Javadoc site
        run: |
          rm -rf gh-pages/api
          cp -rf api/build/docs/javadoc gh-pages/api
      - name: Commit documentation changes
        run: |
          cd gh-pages
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m "Automated API website updates."
          fi
          git push
          cd ..
