name: "Nightly"

on:
  push:
    branches:
      - "nightly"

jobs:
  nightly:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      id-token: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Install JCougar
        run: ./env

      - name: Build Jar with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: paper-standalone:shadowJar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-build"
          prerelease: true
          title: "Nightly Build"
          files: |
            paper-standalone/build/libs/*.jar
