name: Release

on:
  push:
    branches:
      - "ver/*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          GRADLE_GITHUB_USERNAME: ${{ github.actor }}
          GRADLE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Jar with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: paper-standalone:shadowJar
        env:
          GRADLE_GITHUB_USERNAME: ${{ github.actor }}
          GRADLE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-build"
          prerelease: false
          title: "Latest Release Build"
          files: |
            paper-standalone/build/libs/*.jar
