name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version without v-prefix
        required: true
      pre-release:
        type: boolean
        description: Should this be a pre-release?
        default: false

jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          settings-path: "${{ github.workspace }}"

      - name: Build Jar with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: paper-standalone:shadowJar

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "paper-standalone/build/libs/*.jar"
          bodyFile: "CHANGELOG.md"
          makeLatest: "${{ !github.event.inputs.pre-release }}"
          name: "v${{ github.event.inputs.version }}"
          prerelease: "${{ github.event.inputs.pre-release }}"
          tag: "release/v${{ github.event.inputs.version }}"
